version: '3.8'

services:
  algorithms:
    container_name: algorithms
    image: 'algorithms'
    tty: true
    build:
      context: .
      dockerfile: .docker/Dockerfile
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
