version: '3.8'

services:
  playground:
    container_name: playground
    image: 'playground'
    tty: true
    build:
      context: .
      dockerfile: .docker/Dockerfile
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
